// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgaanqtouegdotsrsinh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYWFucXRvdWVnZG90c3JzaW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjEyOTAsImV4cCI6MjA2NTEzNzI5MH0.JSTZiCYVvdc6I3hatLkSJStKnp7R9eMwz8wy8N9BTGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);